### ISSUE TITLE
gulp-sass から postcss-scss に変更できるかどうか

### ISSUE THREAD

**Issue by kesuiket** [super-true/gulp-task-stylesheet#1]
CSS の処理を PostCSS で一貫させたい。

- [gulp-sass](https://www.npmjs.com/package/gulp-sass)
- [postcss-scss](https://www.npmjs.com/package/postcss-scss)

**Comment by kesuiket** [comment]
```css
const sass = require('gulp-sass');
gulp.src(src)
  .pipe(sass({ presision: 10, outputStyle: 'expanded' }))
```
:point_down:
```css
const scss = require('postcss-scss');
gulp.src(src)
  .pipe(postcss(processors, { syntax: scss }))
```

インデントやスペースなど、処理が少し違うけどひとまずこれで様子見。
```css
/* postcss-scss */
{
  -webkit-user-select: none;
  -moz-user-select: none;
  -ms-user-select: none;
  user-select: none;
}

/* gulp-sass */
{
  -webkit-user-select: none;
     -moz-user-select: none;
      -ms-user-select: none;
          user-select: none;
}
```
